### PR TITLE
Add Other language to compute NCLOC

### PR DESCRIPTION
**Pull request by stas-vilchik**
I don't know Java, but I want to be a super-hero!

### CODE REVIEW

**Comment by fmallet** [comment]
Looks like you're ready to become a Java developer @stas-vilchik !!! My proposal is the following one: the snapshot version of the Generic Coverage Plugin is already deployed on Dory -> So goal is reached, you're starting becoming a super-hero :). From there I'm swearing to convince the core team (cc: @simonbrandhof ) to fix https://jira.codehaus.org/browse/SONAR-5077 quickly to make this feature a core feature.

**Comment by dbolkensteyn** [comment]
@fmallet Do you mean that after https://jira.codehaus.org/browse/SONAR-5077, the developer cockpit will be based on "lines" (automatically fed by the platform) rather than "lines of code" ?

That the only thing I dislike about this pull request, the little hack to approximate "lines of code" (by excluding blank lines). For "lines", the computation is language agonistic.

**Comment by simonbrandhof** [comment]
FYI https://jira.codehaus.org/browse/SONAR-5077 is fixed in 5.1 (still under testing), so this PR can be closed.

**Comment by dbolkensteyn** [comment]
Thank you @simonbrandhof - I am closing it then

**Pull request closed without merging**
